<?xml version="1.0" encoding="UTF-8"?>
<Layout version="1.6.1">
  <Mode>Vertical</Mode>
  <X>73</X>
  <Y>95</Y>
  <VerticalWidth>1120</VerticalWidth>
  <VerticalHeight>272</VerticalHeight>
  <HorizontalWidth>-1</HorizontalWidth>
  <HorizontalHeight>-1</HorizontalHeight>
  <Settings>
    <TextColor>FFFFFFFF</TextColor>
    <BackgroundColor>FF5F417B</BackgroundColor>
    <BackgroundColor2>FF523A6B</BackgroundColor2>
    <ThinSeparatorsColor>03FFFFFF</ThinSeparatorsColor>
    <SeparatorsColor>24FFFFFF</SeparatorsColor>
    <PersonalBestColor>FFFFFFFF</PersonalBestColor>
    <AheadGainingTimeColor>FFFFFFFF</AheadGainingTimeColor>
    <AheadLosingTimeColor>FFFFFFFF</AheadLosingTimeColor>
    <BehindGainingTimeColor>FFFFFFFF</BehindGainingTimeColor>
    <BehindLosingTimeColor>FFFFFFFF</BehindLosingTimeColor>
    <BestSegmentColor>FFFFFFFF</BestSegmentColor>
    <UseRainbowColor>False</UseRainbowColor>
    <NotRunningColor>FFFFFFFF</NotRunningColor>
    <PausedColor>FF7A7A7A</PausedColor>
    <TextOutlineColor>00000000</TextOutlineColor>
    <ShadowsColor>80000000</ShadowsColor>
    <TimesFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAABtTdXBlciBbTWFyaW9dIFNjcmlwdCAyIERlbW8AAEBBBfz///8YU3lzdGVtLkRyYXdpbmcuRm9udFN0eWxlAQAAAAd2YWx1ZV9fAAgCAAAAAQAAAAX7////G1N5c3RlbS5EcmF3aW5nLkdyYXBoaWNzVW5pdAEAAAAHdmFsdWVfXwAIAgAAAAMAAAAL]]></TimesFont>
    <TimerFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAABtTdXBlciBbTWFyaW9dIFNjcmlwdCAyIERlbW8AAC9CBfz///8YU3lzdGVtLkRyYXdpbmcuRm9udFN0eWxlAQAAAAd2YWx1ZV9fAAgCAAAAAQAAAAX7////G1N5c3RlbS5EcmF3aW5nLkdyYXBoaWNzVW5pdAEAAAAHdmFsdWVfXwAIAgAAAAIAAAAL]]></TimerFont>
    <TextFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAABtTdXBlciBbTWFyaW9dIFNjcmlwdCAyIERlbW8AACBBBfz///8YU3lzdGVtLkRyYXdpbmcuRm9udFN0eWxlAQAAAAd2YWx1ZV9fAAgCAAAAAAAAAAX7////G1N5c3RlbS5EcmF3aW5nLkdyYXBoaWNzVW5pdAEAAAAHdmFsdWVfXwAIAgAAAAMAAAAL]]></TextFont>
    <AlwaysOnTop>False</AlwaysOnTop>
    <ShowBestSegments>False</ShowBestSegments>
    <AntiAliasing>True</AntiAliasing>
    <DropShadows>True</DropShadows>
    <BackgroundType>SolidColor</BackgroundType>
    <BackgroundImage />
    <ImageOpacity>1</ImageOpacity>
    <ImageBlur>0</ImageBlur>
    <Opacity>1</Opacity>
    <MousePassThroughWhileRunning>False</MousePassThroughWhileRunning>
  </Settings>
  <Components>
    <Component>
      <Path>LiveSplit.Title.dll</Path>
      <Settings>
        <Version>1.7.3</Version>
        <ShowGameName>True</ShowGameName>
        <ShowCategoryName>True</ShowCategoryName>
        <ShowAttemptCount>True</ShowAttemptCount>
        <ShowFinishedRunsCount>False</ShowFinishedRunsCount>
        <OverrideTitleFont>True</OverrideTitleFont>
        <OverrideTitleColor>False</OverrideTitleColor>
        <TitleFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAABtTdXBlciBbTWFyaW9dIFNjcmlwdCAyIERlbW8AAGBBBfz///8YU3lzdGVtLkRyYXdpbmcuRm9udFN0eWxlAQAAAAd2YWx1ZV9fAAgCAAAAAAAAAAX7////G1N5c3RlbS5EcmF3aW5nLkdyYXBoaWNzVW5pdAEAAAAHdmFsdWVfXwAIAgAAAAMAAAAL]]></TitleFont>
        <SingleLine>False</SingleLine>
        <TitleColor>FFFFFFFF</TitleColor>
        <BackgroundColor>002A2A2A</BackgroundColor>
        <BackgroundColor2>00131313</BackgroundColor2>
        <BackgroundGradient>Vertical</BackgroundGradient>
        <DisplayGameIcon>True</DisplayGameIcon>
        <ShowRegion>False</ShowRegion>
        <ShowPlatform>False</ShowPlatform>
        <ShowVariables>True</ShowVariables>
        <TextAlignment>2</TextAlignment>
      </Settings>
    </Component>
    <Component>
      <Path>
      </Path>
      <Settings />
    </Component>
    <Component>
      <Path>LiveSplit.Timer.dll</Path>
      <Settings>
        <Version>1.5</Version>
        <TimerHeight>50</TimerHeight>
        <TimerWidth>225</TimerWidth>
        <TimerFormat>00:00:01</TimerFormat>
        <OverrideSplitColors>False</OverrideSplitColors>
        <ShowGradient>True</ShowGradient>
        <TimerColor>FFFFFFFF</TimerColor>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>00FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <CenterTimer>True</CenterTimer>
        <TimingMethod>Current Timing Method</TimingMethod>
        <DecimalsSize>35</DecimalsSize>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.Sound.dll</Path>
      <Settings>
        <Version>1.6</Version>
        <Split>
        </Split>
        <SplitAheadGaining>
        </SplitAheadGaining>
        <SplitAheadLosing>
        </SplitAheadLosing>
        <SplitBehindGaining>
        </SplitBehindGaining>
        <SplitBehindLosing>
        </SplitBehindLosing>
        <BestSegment>
        </BestSegment>
        <UndoSplit>
        </UndoSplit>
        <SkipSplit>
        </SkipSplit>
        <PersonalBest>
        </PersonalBest>
        <NotAPersonalBest>
        </NotAPersonalBest>
        <Reset>C:\StreamAssets\Alerts\Game-over-yeah.mp3</Reset>
        <Pause>
        </Pause>
        <Resume>
        </Resume>
        <StartTimer>
        </StartTimer>
        <OutputDevice>0</OutputDevice>
        <SplitVolume>100</SplitVolume>
        <SplitAheadGainingVolume>100</SplitAheadGainingVolume>
        <SplitAheadLosingVolume>100</SplitAheadLosingVolume>
        <SplitBehindGainingVolume>100</SplitBehindGainingVolume>
        <SplitBehindLosingVolume>100</SplitBehindLosingVolume>
        <BestSegmentVolume>100</BestSegmentVolume>
        <UndoSplitVolume>100</UndoSplitVolume>
        <SkipSplitVolume>100</SkipSplitVolume>
        <PersonalBestVolume>100</PersonalBestVolume>
        <NotAPersonalBestVolume>100</NotAPersonalBestVolume>
        <ResetVolume>100</ResetVolume>
        <PauseVolume>100</PauseVolume>
        <ResumeVolume>100</ResumeVolume>
        <StartTimerVolume>100</StartTimerVolume>
        <GeneralVolume>100</GeneralVolume>
      </Settings>
    </Component>
    <Component>
      <Path>
      </Path>
      <Settings />
    </Component>
    <Component>
      <Path>LiveSplit.SumOfBest.dll</Path>
      <Settings>
        <Version>1.4</Version>
        <TextColor>FFFFFFFF</TextColor>
        <OverrideTextColor>False</OverrideTextColor>
        <TimeColor>FFFFFFFF</TimeColor>
        <OverrideTimeColor>False</OverrideTimeColor>
        <Accuracy>Seconds</Accuracy>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>00FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <Display2Rows>False</Display2Rows>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.TotalPlaytime.dll</Path>
      <Settings>
        <Version>1.6</Version>
        <TextColor>FFFFFFFF</TextColor>
        <OverrideTextColor>False</OverrideTextColor>
        <TimeColor>FFFFFFFF</TimeColor>
        <OverrideTimeColor>False</OverrideTimeColor>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>00FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <Display2Rows>False</Display2Rows>
        <ShowTotalHours>True</ShowTotalHours>
      </Settings>
    </Component>
    <Component>
      <Path>SpeedGuidesLive.dll</Path>
      <Settings>
        <Version>1.3.1</Version>
        <FontName>Consolas</FontName>
        <FontSize>12</FontSize>
        <BGColor.R>16</BGColor.R>
        <BGColor.G>16</BGColor.G>
        <BGColor.B>16</BGColor.B>
        <TXTColor.R>255</TXTColor.R>
        <TXTColor.G>255</TXTColor.G>
        <TXTColor.B>255</TXTColor.B>
        <ActiveSplitTxtPath>
        </ActiveSplitTxtPath>
        <WindowPos.X>76</WindowPos.X>
        <WindowPos.Y>391</WindowPos.Y>
        <WindowSize.Width>581</WindowSize.Width>
        <WindowSize.Height>451</WindowSize.Height>
        <MarkdownEnabled>True</MarkdownEnabled>
      </Settings>
    </Component>
    <Component>
      <Path>
      </Path>
      <Settings />
    </Component>
  </Components>
</Layout>